import { v4 as uuid } from "uuid";
import banglesCat from "../asserts/category-images/banglesCat.jpg";
import earringsCat from "../asserts/category-images/earringsCat.jpg";
import necklaceCat from "../asserts/category-images/necklaceCat.jpg";
import pendantCat from "../asserts/category-images/pendantCat.jpg";
import ringCat from "../asserts/category-images/ringCat.jpg";


const categoryList = [
    {"_id":uuid(),
    "categoryName":"Rings",
    "image":ringCat ,
    "filterBy":"CATEGORY-FILTER-RINGS",
    },
    {"_id":uuid(),
    "categoryName":"Necklace",
    "image":necklaceCat ,
    "filterBy":"CATEGORY-FILTER-NECKLACE",
    },
    {"_id":uuid(),
    "categoryName":"Earrings",
    "image":earringsCat ,
    "filterBy":"CATEGORY-FILTER-EARRINGS",
    },
    {"_id":uuid(),
    "categoryName":"Bangles",
    "image":banglesCat ,
    "filterBy":"CATEGORY-FILTER-BANGLES",
    },
    {"_id":uuid(),
    "categoryName":"Pendants",
    "image":pendantCat ,
    "filterBy":"CATEGORY-FILTER-PENDANTS",
    },
    {"_id":uuid(),
    "categoryName":"Earrings",
    "image":earringsCat ,
    "filterBy":"CATEGORY-FILTER-EARRINGS",
    },  
]

const productsList = 
[
    {
        "_id":uuid(),
        "image":ringCat,
        "name":"Embrace Ring",
        "subText":"by GIVA jewellery",
        "rating":4.6,
        "price":4000,
        "originalPrice":4500,
        "category":"rings",  
        "cartQuantity":1,
    },
    {
        "_id":uuid(),
        "image":necklaceCat,
        "name":"Stoned Necklace",
        "subText":"by GIVA jewellery",
        "rating":3.5,
        "price":22000,
        "originalPrice":25000,
        "category":"necklace", 
        "cartQuantity":1, 
    },
    {
        "_id":uuid(),
        "image":pendantCat,
        "name":"Drop pendant",
        "subText":"by yellow jewellery",
        "rating":4.8,
        "price":9999,
        "originalPrice":10999,
        "category":"pendents", 
        "cartQuantity":1, 
    },
    {
        "_id":uuid(),
        "image":ringCat,
        "name":"Band Ring",
        "subText":"plated silver stone",
        "rating":3.8,
        "price":9500,
        "originalPrice":10000,
        "category":"rings",  
        "cartQuantity":1,
    },
    {
        "_id":uuid(),
        "image":necklaceCat,
        "name":"Classic necklace",
        "subText":"by yellow gold jewellery",
        "rating":2.5,
        "price":15000,
        "originalPrice":17000,
        "category":"necklace", 
        "cartQuantity":1, 
    },
    {
        "_id":uuid(),
        "image":banglesCat,
        "name":"Stoned bangle",
        "subText":"by tej jewellery",
        "rating":4.5,
        "price":18000,
        "originalPrice":20000,
        "category":"bangles",  
        "cartQuantity":1,
    },
    {
        "_id":uuid(),
        "image":ringCat,
        "name":"Lettered Ring",
        "subText":"by yellow gold jewellery",
        "rating":3.5,
        "price":8000,
        "originalPrice":8500,
        "category":"rings",  
        "cartQuantity":1,
     },
    {
        "_id":uuid(),
        "image":pendantCat,
        "name":"Stoned pendant",
        "subText":"by ahalya jewellery",
        "rating":2.8,
        "price":7999,
        "originalPrice":10000,
        "category":"pendents", 
        "cartQuantity":1, 
    },
    {
        "_id":uuid(),
        "image":earringsCat,
        "name":"Classic earrings",
        "subText":"by yellow jewellery",
        "rating":4.8,
        "price":10999,
        "originalPrice":16000,
        "category":"earrings", 
        "cartQuantity":1, 
    },
    {
        "_id":uuid(),
        "image":banglesCat,
        "name":"stoned bangle",
        "subText":"by yellow jewellery",
        "rating":3.7,
        "price":7000,
        "originalPrice":9000,
        "category":"bangles",  
        "cartQuantity":1,
    },   
]

export {categoryList,productsList}